# Generated by Django 5.1.4 on 2024-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.URLField(),
        ),
    ]
