# Generated by Django 5.1.4 on 2024-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
